services:
  dbtest:
    image: postgis/postgis
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      dbtest:
        condition: service_healthy

  backend:
    build: ./
    ports:
      - 5000:5000
    restart: always
    env_file:
      - ./.env
    depends_on:
      dbtest:
        condition: service_healthy
    volumes:
      - ./src:/app/src
    command: npm run dev
    healthcheck:
      test: 'curl --fail --request POST --header ''content-type: application/json'' --url ''http://localhost:5000/'' --data ''{"query":"query { __typename }"}'' || exit 1'
      interval: 5s
      timeout: 5s
      retries: 10
