version: '3.8'
services:
  back:
    image: vantej/wildrent-api
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: ${ POSTGRES_USER }
      POSTGRES_PASSWORD: ${ POSTGRES_PASSWORD }
      POSTGRES_DB: ${ POSTGRES_DB }
      PGDATA: /var/lib/postgresql/data/customDataFolder
    volumes:
      - ./dbData:/var/lib/postgresql/data/customDataFolder
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${ POSTGRES_DB } -U ${ POSTGRES_USER }"]
      interval: 5s
      timeout: 5s
      retries: 10