version: '3.8'
services:
  back:
    build:
      dockerfile: "Dockerfile"
      command: npm install && npm run test
    volumes:
      - ./:/app:rw,cached

      - /app/node_modules
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: wildRent
      POSTGRES_PASSWORD: wildRent
      POSTGRES_DB: wildRent
      PGDATA: /var/lib/postgresql/data/customDataFolder
    volumes:
      - ./dbData:/var/lib/postgresql/data/customDataFolder
    ports:
      - 6000:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d wildRent -U wildRent"]
      interval: 5s
      timeout: 5s
      retries: 10
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      db:
        condition: service_healthy