name: test with db

on: push

jobs:
  test-back:
    runs-on: ubuntu-latest
    container: node:16

    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: wildRent
          POSTGRES_PASSWORD: wildRent
          POSTGRES_DB: wildRent
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
        env:
          JWT_SECRET_KEY: toto
          MJ_APIKEY_PUBLIC:  ${{ secrets.MJ_APIKEY_PUBLIC }}
          MJ_APIKEY_PRIVATE:  ${{ secrets.MJ_APIKEY_PRIVATE }}

        