name: test with db

on: push

jobs:
  test-back:
    runs-on: ubuntu-latest
    container: node:16

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Start containers and run tests
        run: docker-compose -f "docker-compose.test.yml" up -d --build
        env:
          JWT_SECRET_KEY: toto
      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.test.yml" down